language: python

python:
  - 3.6

bundler_args: --retry 3

install:
  - sudo apt-get update
  - ./utils/travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml
  - source activate student_project
  - pip install git+https://github.com/OpenSourceEconomics/respy@7d035c0dcd1ea1d17cd02741408411e7eec5c5b8
script:
  - travis_wait python utils/travis_runner.py
