language: python

python:
  - 3.6

bundler_args: --retry 3

install:
  - sudo apt-get update
  - ./utils/travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml
  - source activate student_project
  - pip install git+https://github.com/OpenSourceEconomics/respy@6650a003f26b55a0147b32fad9e1ff0b96e6719b

script:
  - travis_wait python utils/travis_runner.py
