language: python

python:
  - 3.6

bundler_args: --retry 3

install:
  - sudo apt-get update
  - ./utils/travis_miniconda.sh
  - PATH="$HOME/miniconda/bin:$PATH"
  - conda env create -f environment.yml
  - source activate student_project
  - pip install git+https://github.com/OpenSourceEconomics/respy@d09b560abf1de90cd9b72b9b53578fa3156d2e50

script:
  - travis_wait python utils/travis_runner.py
